import type { Card } from "./gameTypes";

export const TMT_DECK: Card[] = [
  {
    id: "L1-001",
    level: 1,
    type: "question",
    text: "What is a small gesture that makes you feel instantly closer to someone?",
  },
  {
    id: "L1-002",
    level: 1,
    type: "question",
    text: "When do you feel most relaxed around another person?",
  },
  {
    id: "L1-003",
    level: 1,
    type: "question",
    text: "Share a lighthearted memory that still makes you smile.",
  },
  {
    id: "L1-004",
    level: 1,
    type: "question",
    text: "What kind of compliment do you secretly love to hear?",
  },
  {
    id: "L1-005",
    level: 1,
    type: "question",
    text: "How do you like someone to show they are paying attention to you?",
  },
  {
    id: "L1-006",
    level: 1,
    type: "question",
    text: "Describe a moment when you felt cute or attractive in your own way.",
  },
  {
    id: "L1-007",
    level: 1,
    type: "question",
    text: "What kind of first date makes you feel comfortable and excited?",
  },
  {
    id: "L1-008",
    level: 1,
    type: "question",
    text: "When you flirt, what do you think gives you away?",
  },
  {
    id: "L1-009",
    level: 1,
    type: "question",
    text: "What is a tiny act of kindness that would completely make your day?",
  },
  {
    id: "L1-010",
    level: 1,
    type: "question",
    text: "When do you feel most confident walking into a room?",
  },
  {
    id: "L1-011",
    level: 1,
    type: "question",
    text: "What is a song that makes you feel a little flirty or playful?",
  },
  {
    id: "L1-012",
    level: 1,
    type: "question",
    text: "Describe your ideal cozy night in with someone you like.",
  },
  {
    id: "L1-013",
    level: 1,
    type: "question",
    text: "What non-physical trait instantly makes someone more attractive to you?",
  },
  {
    id: "L1-014",
    level: 1,
    type: "question",
    text: "How do you prefer someone to show interest in you for the first time?",
  },
  {
    id: "L1-015",
    level: 1,
    type: "question",
    text: "Share a moment when a simple text or message made you feel special.",
  },
  {
    id: "L1-016",
    level: 1,
    type: "question",
    text: "What kind of touch feels safe and comforting when you first get close to someone?",
  },
  {
    id: "L1-017",
    level: 1,
    type: "question",
    text: "When do you feel most like your authentic self around others?",
  },
  {
    id: "L1-018",
    level: 1,
    type: "question",
    text: "What is a small ritual you would love to share with a future partner?",
  },
  {
    id: "L1-019",
    level: 1,
    type: "question",
    text: "How do you like to be approached when someone has a crush on you?",
  },
  {
    id: "L1-020",
    level: 1,
    type: "question",
    text: "What body language from someone else instantly catches your attention?",
  },
  {
    id: "L1-021",
    level: 1,
    type: "question",
    text: "What is a small gesture that makes you feel instantly closer to someone? (Reflection #21 for you.)",
  },
  {
    id: "L1-022",
    level: 1,
    type: "question",
    text: "When do you feel most relaxed around another person? (Reflection #22 for you.)",
  },
  {
    id: "L1-023",
    level: 1,
    type: "question",
    text: "Share a lighthearted memory that still makes you smile. (Reflection #23 for you.)",
  },
  {
    id: "L1-024",
    level: 1,
    type: "question",
    text: "What kind of compliment do you secretly love to hear? (Reflection #24 for you.)",
  },
  {
    id: "L1-025",
    level: 1,
    type: "question",
    text: "How do you like someone to show they are paying attention to you? (Reflection #25 for you.)",
  },
  {
    id: "L1-026",
    level: 1,
    type: "question",
    text: "Describe a moment when you felt cute or attractive in your own way. (Reflection #26 for you.)",
  },
  {
    id: "L1-027",
    level: 1,
    type: "question",
    text: "What kind of first date makes you feel comfortable and excited? (Reflection #27 for you.)",
  },
  {
    id: "L1-028",
    level: 1,
    type: "question",
    text: "When you flirt, what do you think gives you away? (Reflection #28 for you.)",
  },
  {
    id: "L1-029",
    level: 1,
    type: "question",
    text: "What is a tiny act of kindness that would completely make your day? (Reflection #29 for you.)",
  },
  {
    id: "L1-030",
    level: 1,
    type: "question",
    text: "When do you feel most confident walking into a room? (Reflection #30 for you.)",
  },
  {
    id: "L1-031",
    level: 1,
    type: "question",
    text: "What is a song that makes you feel a little flirty or playful? (Reflection #31 for you.)",
  },
  {
    id: "L1-032",
    level: 1,
    type: "question",
    text: "Describe your ideal cozy night in with someone you like. (Reflection #32 for you.)",
  },
  {
    id: "L1-033",
    level: 1,
    type: "question",
    text: "What non-physical trait instantly makes someone more attractive to you? (Reflection #33 for you.)",
  },
  {
    id: "L1-034",
    level: 1,
    type: "question",
    text: "How do you prefer someone to show interest in you for the first time? (Reflection #34 for you.)",
  },
  {
    id: "L1-035",
    level: 1,
    type: "question",
    text: "Share a moment when a simple text or message made you feel special. (Reflection #35 for you.)",
  },
  {
    id: "L1-036",
    level: 1,
    type: "question",
    text: "What kind of touch feels safe and comforting when you first get close to someone? (Reflection #36 for you.)",
  },
  {
    id: "L1-037",
    level: 1,
    type: "question",
    text: "When do you feel most like your authentic self around others? (Reflection #37 for you.)",
  },
  {
    id: "L1-038",
    level: 1,
    type: "question",
    text: "What is a small ritual you would love to share with a future partner? (Reflection #38 for you.)",
  },
  {
    id: "L1-039",
    level: 1,
    type: "question",
    text: "How do you like to be approached when someone has a crush on you? (Reflection #39 for you.)",
  },
  {
    id: "L1-040",
    level: 1,
    type: "question",
    text: "What body language from someone else instantly catches your attention? (Reflection #40 for you.)",
  },
  {
    id: "L1-041",
    level: 1,
    type: "question",
    text: "What is a small gesture that makes you feel instantly closer to someone? (Reflection #41 for you.)",
  },
  {
    id: "L1-042",
    level: 1,
    type: "question",
    text: "When do you feel most relaxed around another person? (Reflection #42 for you.)",
  },
  {
    id: "L1-043",
    level: 1,
    type: "question",
    text: "Share a lighthearted memory that still makes you smile. (Reflection #43 for you.)",
  },
  {
    id: "L1-044",
    level: 1,
    type: "question",
    text: "What kind of compliment do you secretly love to hear? (Reflection #44 for you.)",
  },
  {
    id: "L1-045",
    level: 1,
    type: "question",
    text: "How do you like someone to show they are paying attention to you? (Reflection #45 for you.)",
  },
  {
    id: "L1-046",
    level: 1,
    type: "question",
    text: "Describe a moment when you felt cute or attractive in your own way. (Reflection #46 for you.)",
  },
  {
    id: "L1-047",
    level: 1,
    type: "question",
    text: "What kind of first date makes you feel comfortable and excited? (Reflection #47 for you.)",
  },
  {
    id: "L1-048",
    level: 1,
    type: "question",
    text: "When you flirt, what do you think gives you away? (Reflection #48 for you.)",
  },
  {
    id: "L1-049",
    level: 1,
    type: "question",
    text: "What is a tiny act of kindness that would completely make your day? (Reflection #49 for you.)",
  },
  {
    id: "L1-050",
    level: 1,
    type: "question",
    text: "When do you feel most confident walking into a room? (Reflection #50 for you.)",
  },
  {
    id: "L1-051",
    level: 1,
    type: "question",
    text: "What is a song that makes you feel a little flirty or playful? (Reflection #51 for you.)",
  },
  {
    id: "L1-052",
    level: 1,
    type: "question",
    text: "Describe your ideal cozy night in with someone you like. (Reflection #52 for you.)",
  },
  {
    id: "L1-053",
    level: 1,
    type: "question",
    text: "What non-physical trait instantly makes someone more attractive to you? (Reflection #53 for you.)",
  },
  {
    id: "L1-054",
    level: 1,
    type: "question",
    text: "How do you prefer someone to show interest in you for the first time? (Reflection #54 for you.)",
  },
  {
    id: "L1-055",
    level: 1,
    type: "question",
    text: "Share a moment when a simple text or message made you feel special. (Reflection #55 for you.)",
  },
  {
    id: "L1-056",
    level: 1,
    type: "question",
    text: "What kind of touch feels safe and comforting when you first get close to someone? (Reflection #56 for you.)",
  },
  {
    id: "L1-057",
    level: 1,
    type: "question",
    text: "When do you feel most like your authentic self around others? (Reflection #57 for you.)",
  },
  {
    id: "L1-058",
    level: 1,
    type: "question",
    text: "What is a small ritual you would love to share with a future partner? (Reflection #58 for you.)",
  },
  {
    id: "L1-059",
    level: 1,
    type: "question",
    text: "How do you like to be approached when someone has a crush on you? (Reflection #59 for you.)",
  },
  {
    id: "L1-060",
    level: 1,
    type: "question",
    text: "What body language from someone else instantly catches your attention? (Reflection #60 for you.)",
  },
  {
    id: "L1-061",
    level: 1,
    type: "question",
    text: "What is a small gesture that makes you feel instantly closer to someone? (Reflection #61 for you.)",
  },
  {
    id: "L1-062",
    level: 1,
    type: "question",
    text: "When do you feel most relaxed around another person? (Reflection #62 for you.)",
  },
  {
    id: "L1-063",
    level: 1,
    type: "question",
    text: "Share a lighthearted memory that still makes you smile. (Reflection #63 for you.)",
  },
  {
    id: "L1-064",
    level: 1,
    type: "question",
    text: "What kind of compliment do you secretly love to hear? (Reflection #64 for you.)",
  },
  {
    id: "L1-065",
    level: 1,
    type: "question",
    text: "How do you like someone to show they are paying attention to you? (Reflection #65 for you.)",
  },
  {
    id: "L1-066",
    level: 1,
    type: "question",
    text: "Describe a moment when you felt cute or attractive in your own way. (Reflection #66 for you.)",
  },
  {
    id: "L1-067",
    level: 1,
    type: "question",
    text: "What kind of first date makes you feel comfortable and excited? (Reflection #67 for you.)",
  },
  {
    id: "L1-068",
    level: 1,
    type: "question",
    text: "When you flirt, what do you think gives you away? (Reflection #68 for you.)",
  },
  {
    id: "L1-069",
    level: 1,
    type: "question",
    text: "What is a tiny act of kindness that would completely make your day? (Reflection #69 for you.)",
  },
  {
    id: "L1-070",
    level: 1,
    type: "question",
    text: "When do you feel most confident walking into a room? (Reflection #70 for you.)",
  },
  {
    id: "L1-071",
    level: 1,
    type: "question",
    text: "What is a song that makes you feel a little flirty or playful? (Reflection #71 for you.)",
  },
  {
    id: "L1-072",
    level: 1,
    type: "question",
    text: "Describe your ideal cozy night in with someone you like. (Reflection #72 for you.)",
  },
  {
    id: "L1-073",
    level: 1,
    type: "question",
    text: "What non-physical trait instantly makes someone more attractive to you? (Reflection #73 for you.)",
  },
  {
    id: "L1-074",
    level: 1,
    type: "question",
    text: "How do you prefer someone to show interest in you for the first time? (Reflection #74 for you.)",
  },
  {
    id: "L1-075",
    level: 1,
    type: "question",
    text: "Share a moment when a simple text or message made you feel special. (Reflection #75 for you.)",
  },
  {
    id: "L1-076",
    level: 1,
    type: "question",
    text: "What kind of touch feels safe and comforting when you first get close to someone? (Reflection #76 for you.)",
  },
  {
    id: "L1-077",
    level: 1,
    type: "question",
    text: "When do you feel most like your authentic self around others? (Reflection #77 for you.)",
  },
  {
    id: "L1-078",
    level: 1,
    type: "question",
    text: "What is a small ritual you would love to share with a future partner? (Reflection #78 for you.)",
  },
  {
    id: "L1-079",
    level: 1,
    type: "question",
    text: "How do you like to be approached when someone has a crush on you? (Reflection #79 for you.)",
  },
  {
    id: "L1-080",
    level: 1,
    type: "question",
    text: "What body language from someone else instantly catches your attention? (Reflection #80 for you.)",
  },
  {
    id: "L1-081",
    level: 1,
    type: "question",
    text: "What is a small gesture that makes you feel instantly closer to someone? (Reflection #81 for you.)",
  },
  {
    id: "L1-082",
    level: 1,
    type: "question",
    text: "When do you feel most relaxed around another person? (Reflection #82 for you.)",
  },
  {
    id: "L1-083",
    level: 1,
    type: "question",
    text: "Share a lighthearted memory that still makes you smile. (Reflection #83 for you.)",
  },
  {
    id: "L1-084",
    level: 1,
    type: "question",
    text: "What kind of compliment do you secretly love to hear? (Reflection #84 for you.)",
  },
  {
    id: "L1-085",
    level: 1,
    type: "question",
    text: "How do you like someone to show they are paying attention to you? (Reflection #85 for you.)",
  },
  {
    id: "L1-086",
    level: 1,
    type: "question",
    text: "Describe a moment when you felt cute or attractive in your own way. (Reflection #86 for you.)",
  },
  {
    id: "L1-087",
    level: 1,
    type: "question",
    text: "What kind of first date makes you feel comfortable and excited? (Reflection #87 for you.)",
  },
  {
    id: "L1-088",
    level: 1,
    type: "question",
    text: "When you flirt, what do you think gives you away? (Reflection #88 for you.)",
  },
  {
    id: "L1-089",
    level: 1,
    type: "question",
    text: "What is a tiny act of kindness that would completely make your day? (Reflection #89 for you.)",
  },
  {
    id: "L1-090",
    level: 1,
    type: "question",
    text: "When do you feel most confident walking into a room? (Reflection #90 for you.)",
  },
  {
    id: "L1-091",
    level: 1,
    type: "question",
    text: "What is a song that makes you feel a little flirty or playful? (Reflection #91 for you.)",
  },
  {
    id: "L1-092",
    level: 1,
    type: "question",
    text: "Describe your ideal cozy night in with someone you like. (Reflection #92 for you.)",
  },
  {
    id: "L1-093",
    level: 1,
    type: "question",
    text: "What non-physical trait instantly makes someone more attractive to you? (Reflection #93 for you.)",
  },
  {
    id: "L1-094",
    level: 1,
    type: "question",
    text: "How do you prefer someone to show interest in you for the first time? (Reflection #94 for you.)",
  },
  {
    id: "L1-095",
    level: 1,
    type: "question",
    text: "Share a moment when a simple text or message made you feel special. (Reflection #95 for you.)",
  },
  {
    id: "L1-096",
    level: 1,
    type: "question",
    text: "What kind of touch feels safe and comforting when you first get close to someone? (Reflection #96 for you.)",
  },
  {
    id: "L1-097",
    level: 1,
    type: "question",
    text: "When do you feel most like your authentic self around others? (Reflection #97 for you.)",
  },
  {
    id: "L1-098",
    level: 1,
    type: "question",
    text: "What is a small ritual you would love to share with a future partner? (Reflection #98 for you.)",
  },
  {
    id: "L1-099",
    level: 1,
    type: "question",
    text: "How do you like to be approached when someone has a crush on you? (Reflection #99 for you.)",
  },
  {
    id: "L1-100",
    level: 1,
    type: "question",
    text: "What body language from someone else instantly catches your attention? (Reflection #100 for you.)",
  },
  {
    id: "L2-001",
    level: 2,
    type: "question",
    text: "What is one emotional need you wish partners understood better about you?",
  },
  {
    id: "L2-002",
    level: 2,
    type: "question",
    text: "Describe a time you felt truly emotionally safe with someone.",
  },
  {
    id: "L2-003",
    level: 2,
    type: "question",
    text: "How has your view of love changed over the years?",
  },
  {
    id: "L2-004",
    level: 2,
    type: "question",
    text: "What makes you feel most cared for during a vulnerable moment?",
  },
  {
    id: "L2-005",
    level: 2,
    type: "question",
    text: "Share a time when you communicated a boundary well.",
  },
  {
    id: "L2-006",
    level: 2,
    type: "question",
    text: "How do you like to repair a misunderstanding or conflict with someone you care about?",
  },
  {
    id: "L2-007",
    level: 2,
    type: "question",
    text: "What does emotional intimacy mean to you in your own words?",
  },
  {
    id: "L2-008",
    level: 2,
    type: "question",
    text: "Describe a moment when someone handled your feelings with real care.",
  },
  {
    id: "L2-009",
    level: 2,
    type: "question",
    text: "What is something you find difficult to talk about, even with people you trust?",
  },
  {
    id: "L2-010",
    level: 2,
    type: "question",
    text: "How do you know when you are starting to truly trust someone?",
  },
  {
    id: "L2-011",
    level: 2,
    type: "question",
    text: "What is one belief about relationships you are currently rethinking?",
  },
  {
    id: "L2-012",
    level: 2,
    type: "question",
    text: "Describe a time you felt proud of yourself for being honest about your needs.",
  },
  {
    id: "L2-013",
    level: 2,
    type: "question",
    text: "How do you prefer someone to support you when you are overwhelmed?",
  },
  {
    id: "L2-014",
    level: 2,
    type: "question",
    text: "What kind of check-in message from a partner means the most to you?",
  },
  {
    id: "L2-015",
    level: 2,
    type: "question",
    text: "Share a tender memory that still feels important to your story.",
  },
  {
    id: "L2-016",
    level: 2,
    type: "question",
    text: "What is one fear you have about being fully seen by someone?",
  },
  {
    id: "L2-017",
    level: 2,
    type: "question",
    text: "How do you like to reconnect after distance or conflict?",
  },
  {
    id: "L2-018",
    level: 2,
    type: "question",
    text: "What is something you need in order to feel safe opening up about difficult topics?",
  },
  {
    id: "L2-019",
    level: 2,
    type: "question",
    text: "Describe a moment in your life when intimacy felt healing.",
  },
  {
    id: "L2-020",
    level: 2,
    type: "question",
    text: "When do you feel most emotionally connected during physical closeness?",
  },
  {
    id: "L2-021",
    level: 2,
    type: "question",
    text: "What is one emotional need you wish partners understood better about you? (Reflection #21 for you.)",
  },
  {
    id: "L2-022",
    level: 2,
    type: "question",
    text: "Describe a time you felt truly emotionally safe with someone. (Reflection #22 for you.)",
  },
  {
    id: "L2-023",
    level: 2,
    type: "question",
    text: "How has your view of love changed over the years? (Reflection #23 for you.)",
  },
  {
    id: "L2-024",
    level: 2,
    type: "question",
    text: "What makes you feel most cared for during a vulnerable moment? (Reflection #24 for you.)",
  },
  {
    id: "L2-025",
    level: 2,
    type: "question",
    text: "Share a time when you communicated a boundary well. (Reflection #25 for you.)",
  },
  {
    id: "L2-026",
    level: 2,
    type: "question",
    text: "How do you like to repair a misunderstanding or conflict with someone you care about? (Reflection #26 for you.)",
  },
  {
    id: "L2-027",
    level: 2,
    type: "question",
    text: "What does emotional intimacy mean to you in your own words? (Reflection #27 for you.)",
  },
  {
    id: "L2-028",
    level: 2,
    type: "question",
    text: "Describe a moment when someone handled your feelings with real care. (Reflection #28 for you.)",
  },
  {
    id: "L2-029",
    level: 2,
    type: "question",
    text: "What is something you find difficult to talk about, even with people you trust? (Reflection #29 for you.)",
  },
  {
    id: "L2-030",
    level: 2,
    type: "question",
    text: "How do you know when you are starting to truly trust someone? (Reflection #30 for you.)",
  },
  {
    id: "L2-031",
    level: 2,
    type: "question",
    text: "What is one belief about relationships you are currently rethinking? (Reflection #31 for you.)",
  },
  {
    id: "L2-032",
    level: 2,
    type: "question",
    text: "Describe a time you felt proud of yourself for being honest about your needs. (Reflection #32 for you.)",
  },
  {
    id: "L2-033",
    level: 2,
    type: "question",
    text: "How do you prefer someone to support you when you are overwhelmed? (Reflection #33 for you.)",
  },
  {
    id: "L2-034",
    level: 2,
    type: "question",
    text: "What kind of check-in message from a partner means the most to you? (Reflection #34 for you.)",
  },
  {
    id: "L2-035",
    level: 2,
    type: "question",
    text: "Share a tender memory that still feels important to your story. (Reflection #35 for you.)",
  },
  {
    id: "L2-036",
    level: 2,
    type: "question",
    text: "What is one fear you have about being fully seen by someone? (Reflection #36 for you.)",
  },
  {
    id: "L2-037",
    level: 2,
    type: "question",
    text: "How do you like to reconnect after distance or conflict? (Reflection #37 for you.)",
  },
  {
    id: "L2-038",
    level: 2,
    type: "question",
    text: "What is something you need in order to feel safe opening up about difficult topics? (Reflection #38 for you.)",
  },
  {
    id: "L2-039",
    level: 2,
    type: "question",
    text: "Describe a moment in your life when intimacy felt healing. (Reflection #39 for you.)",
  },
  {
    id: "L2-040",
    level: 2,
    type: "question",
    text: "When do you feel most emotionally connected during physical closeness? (Reflection #40 for you.)",
  },
  {
    id: "L2-041",
    level: 2,
    type: "question",
    text: "What is one emotional need you wish partners understood better about you? (Reflection #41 for you.)",
  },
  {
    id: "L2-042",
    level: 2,
    type: "question",
    text: "Describe a time you felt truly emotionally safe with someone. (Reflection #42 for you.)",
  },
  {
    id: "L2-043",
    level: 2,
    type: "question",
    text: "How has your view of love changed over the years? (Reflection #43 for you.)",
  },
  {
    id: "L2-044",
    level: 2,
    type: "question",
    text: "What makes you feel most cared for during a vulnerable moment? (Reflection #44 for you.)",
  },
  {
    id: "L2-045",
    level: 2,
    type: "question",
    text: "Share a time when you communicated a boundary well. (Reflection #45 for you.)",
  },
  {
    id: "L2-046",
    level: 2,
    type: "question",
    text: "How do you like to repair a misunderstanding or conflict with someone you care about? (Reflection #46 for you.)",
  },
  {
    id: "L2-047",
    level: 2,
    type: "question",
    text: "What does emotional intimacy mean to you in your own words? (Reflection #47 for you.)",
  },
  {
    id: "L2-048",
    level: 2,
    type: "question",
    text: "Describe a moment when someone handled your feelings with real care. (Reflection #48 for you.)",
  },
  {
    id: "L2-049",
    level: 2,
    type: "question",
    text: "What is something you find difficult to talk about, even with people you trust? (Reflection #49 for you.)",
  },
  {
    id: "L2-050",
    level: 2,
    type: "question",
    text: "How do you know when you are starting to truly trust someone? (Reflection #50 for you.)",
  },
  {
    id: "L2-051",
    level: 2,
    type: "question",
    text: "What is one belief about relationships you are currently rethinking? (Reflection #51 for you.)",
  },
  {
    id: "L2-052",
    level: 2,
    type: "question",
    text: "Describe a time you felt proud of yourself for being honest about your needs. (Reflection #52 for you.)",
  },
  {
    id: "L2-053",
    level: 2,
    type: "question",
    text: "How do you prefer someone to support you when you are overwhelmed? (Reflection #53 for you.)",
  },
  {
    id: "L2-054",
    level: 2,
    type: "question",
    text: "What kind of check-in message from a partner means the most to you? (Reflection #54 for you.)",
  },
  {
    id: "L2-055",
    level: 2,
    type: "question",
    text: "Share a tender memory that still feels important to your story. (Reflection #55 for you.)",
  },
  {
    id: "L2-056",
    level: 2,
    type: "question",
    text: "What is one fear you have about being fully seen by someone? (Reflection #56 for you.)",
  },
  {
    id: "L2-057",
    level: 2,
    type: "question",
    text: "How do you like to reconnect after distance or conflict? (Reflection #57 for you.)",
  },
  {
    id: "L2-058",
    level: 2,
    type: "question",
    text: "What is something you need in order to feel safe opening up about difficult topics? (Reflection #58 for you.)",
  },
  {
    id: "L2-059",
    level: 2,
    type: "question",
    text: "Describe a moment in your life when intimacy felt healing. (Reflection #59 for you.)",
  },
  {
    id: "L2-060",
    level: 2,
    type: "question",
    text: "When do you feel most emotionally connected during physical closeness? (Reflection #60 for you.)",
  },
  {
    id: "L2-061",
    level: 2,
    type: "question",
    text: "What is one emotional need you wish partners understood better about you? (Reflection #61 for you.)",
  },
  {
    id: "L2-062",
    level: 2,
    type: "question",
    text: "Describe a time you felt truly emotionally safe with someone. (Reflection #62 for you.)",
  },
  {
    id: "L2-063",
    level: 2,
    type: "question",
    text: "How has your view of love changed over the years? (Reflection #63 for you.)",
  },
  {
    id: "L2-064",
    level: 2,
    type: "question",
    text: "What makes you feel most cared for during a vulnerable moment? (Reflection #64 for you.)",
  },
  {
    id: "L2-065",
    level: 2,
    type: "question",
    text: "Share a time when you communicated a boundary well. (Reflection #65 for you.)",
  },
  {
    id: "L2-066",
    level: 2,
    type: "question",
    text: "How do you like to repair a misunderstanding or conflict with someone you care about? (Reflection #66 for you.)",
  },
  {
    id: "L2-067",
    level: 2,
    type: "question",
    text: "What does emotional intimacy mean to you in your own words? (Reflection #67 for you.)",
  },
  {
    id: "L2-068",
    level: 2,
    type: "question",
    text: "Describe a moment when someone handled your feelings with real care. (Reflection #68 for you.)",
  },
  {
    id: "L2-069",
    level: 2,
    type: "question",
    text: "What is something you find difficult to talk about, even with people you trust? (Reflection #69 for you.)",
  },
  {
    id: "L2-070",
    level: 2,
    type: "question",
    text: "How do you know when you are starting to truly trust someone? (Reflection #70 for you.)",
  },
  {
    id: "L2-071",
    level: 2,
    type: "question",
    text: "What is one belief about relationships you are currently rethinking? (Reflection #71 for you.)",
  },
  {
    id: "L2-072",
    level: 2,
    type: "question",
    text: "Describe a time you felt proud of yourself for being honest about your needs. (Reflection #72 for you.)",
  },
  {
    id: "L2-073",
    level: 2,
    type: "question",
    text: "How do you prefer someone to support you when you are overwhelmed? (Reflection #73 for you.)",
  },
  {
    id: "L2-074",
    level: 2,
    type: "question",
    text: "What kind of check-in message from a partner means the most to you? (Reflection #74 for you.)",
  },
  {
    id: "L2-075",
    level: 2,
    type: "question",
    text: "Share a tender memory that still feels important to your story. (Reflection #75 for you.)",
  },
  {
    id: "L2-076",
    level: 2,
    type: "question",
    text: "What is one fear you have about being fully seen by someone? (Reflection #76 for you.)",
  },
  {
    id: "L2-077",
    level: 2,
    type: "question",
    text: "How do you like to reconnect after distance or conflict? (Reflection #77 for you.)",
  },
  {
    id: "L2-078",
    level: 2,
    type: "question",
    text: "What is something you need in order to feel safe opening up about difficult topics? (Reflection #78 for you.)",
  },
  {
    id: "L2-079",
    level: 2,
    type: "question",
    text: "Describe a moment in your life when intimacy felt healing. (Reflection #79 for you.)",
  },
  {
    id: "L2-080",
    level: 2,
    type: "question",
    text: "When do you feel most emotionally connected during physical closeness? (Reflection #80 for you.)",
  },
  {
    id: "L2-081",
    level: 2,
    type: "question",
    text: "What is one emotional need you wish partners understood better about you? (Reflection #81 for you.)",
  },
  {
    id: "L2-082",
    level: 2,
    type: "question",
    text: "Describe a time you felt truly emotionally safe with someone. (Reflection #82 for you.)",
  },
  {
    id: "L2-083",
    level: 2,
    type: "question",
    text: "How has your view of love changed over the years? (Reflection #83 for you.)",
  },
  {
    id: "L2-084",
    level: 2,
    type: "question",
    text: "What makes you feel most cared for during a vulnerable moment? (Reflection #84 for you.)",
  },
  {
    id: "L2-085",
    level: 2,
    type: "question",
    text: "Share a time when you communicated a boundary well. (Reflection #85 for you.)",
  },
  {
    id: "L2-086",
    level: 2,
    type: "question",
    text: "How do you like to repair a misunderstanding or conflict with someone you care about? (Reflection #86 for you.)",
  },
  {
    id: "L2-087",
    level: 2,
    type: "question",
    text: "What does emotional intimacy mean to you in your own words? (Reflection #87 for you.)",
  },
  {
    id: "L2-088",
    level: 2,
    type: "question",
    text: "Describe a moment when someone handled your feelings with real care. (Reflection #88 for you.)",
  },
  {
    id: "L2-089",
    level: 2,
    type: "question",
    text: "What is something you find difficult to talk about, even with people you trust? (Reflection #89 for you.)",
  },
  {
    id: "L2-090",
    level: 2,
    type: "question",
    text: "How do you know when you are starting to truly trust someone? (Reflection #90 for you.)",
  },
  {
    id: "L2-091",
    level: 2,
    type: "question",
    text: "What is one belief about relationships you are currently rethinking? (Reflection #91 for you.)",
  },
  {
    id: "L2-092",
    level: 2,
    type: "question",
    text: "Describe a time you felt proud of yourself for being honest about your needs. (Reflection #92 for you.)",
  },
  {
    id: "L2-093",
    level: 2,
    type: "question",
    text: "How do you prefer someone to support you when you are overwhelmed? (Reflection #93 for you.)",
  },
  {
    id: "L2-094",
    level: 2,
    type: "question",
    text: "What kind of check-in message from a partner means the most to you? (Reflection #94 for you.)",
  },
  {
    id: "L2-095",
    level: 2,
    type: "question",
    text: "Share a tender memory that still feels important to your story. (Reflection #95 for you.)",
  },
  {
    id: "L2-096",
    level: 2,
    type: "question",
    text: "What is one fear you have about being fully seen by someone? (Reflection #96 for you.)",
  },
  {
    id: "L2-097",
    level: 2,
    type: "question",
    text: "How do you like to reconnect after distance or conflict? (Reflection #97 for you.)",
  },
  {
    id: "L2-098",
    level: 2,
    type: "question",
    text: "What is something you need in order to feel safe opening up about difficult topics? (Reflection #98 for you.)",
  },
  {
    id: "L2-099",
    level: 2,
    type: "question",
    text: "Describe a moment in your life when intimacy felt healing. (Reflection #99 for you.)",
  },
  {
    id: "L2-100",
    level: 2,
    type: "question",
    text: "When do you feel most emotionally connected during physical closeness? (Reflection #100 for you.)",
  },
  {
    id: "L3-001",
    level: 3,
    type: "question",
    text: "What is a part of your story that feels tender to share but important to who you are now?",
  },
  {
    id: "L3-002",
    level: 3,
    type: "question",
    text: "Describe a time you felt deeply unseen or misunderstood in a relationship.",
  },
  {
    id: "L3-003",
    level: 3,
    type: "question",
    text: "What is a fear about intimacy that you rarely say out loud?",
  },
  {
    id: "L3-004",
    level: 3,
    type: "question",
    text: "Share a moment when choosing yourself felt both painful and necessary.",
  },
  {
    id: "L3-005",
    level: 3,
    type: "question",
    text: "How has past hurt shaped the way you protect your heart today?",
  },
  {
    id: "L3-006",
    level: 3,
    type: "question",
    text: "What do you need from someone if you choose to share your hardest memories with them?",
  },
  {
    id: "L3-007",
    level: 3,
    type: "question",
    text: "Describe a time intimacy left you feeling more alone than connected.",
  },
  {
    id: "L3-008",
    level: 3,
    type: "question",
    text: "What is a truth about your desires that you are still learning to accept?",
  },
  {
    id: "L3-009",
    level: 3,
    type: "question",
    text: "When have you felt pressure to be okay when you really were not?",
  },
  {
    id: "L3-010",
    level: 3,
    type: "question",
    text: "What boundary have you held that cost you something, but you would choose again?",
  },
  {
    id: "L3-011",
    level: 3,
    type: "question",
    text: "Share a moment when someone held space for your pain in a way that mattered.",
  },
  {
    id: "L3-012",
    level: 3,
    type: "question",
    text: "How do you carry regret from past relationships, if at all?",
  },
  {
    id: "L3-013",
    level: 3,
    type: "question",
    text: "What is a question about yourself that still feels unanswered?",
  },
  {
    id: "L3-014",
    level: 3,
    type: "question",
    text: "Describe a time you stayed when you knew you needed to leave.",
  },
  {
    id: "L3-015",
    level: 3,
    type: "question",
    text: "How do you know when your body is saying no, even if your mind is confused?",
  },
  {
    id: "L3-016",
    level: 3,
    type: "question",
    text: "What part of your past do you wish could receive more compassion?",
  },
  {
    id: "L3-017",
    level: 3,
    type: "question",
    text: "When have you surprised yourself with your resilience?",
  },
  {
    id: "L3-018",
    level: 3,
    type: "question",
    text: "What is one thing you hope future intimacy will feel like, compared to your past?",
  },
  {
    id: "L3-019",
    level: 3,
    type: "question",
    text: "Describe a moment when you forgave yourself for something difficult.",
  },
  {
    id: "L3-020",
    level: 3,
    type: "question",
    text: "What does true safety in love look like to you, in specific details?",
  },
  {
    id: "L3-021",
    level: 3,
    type: "question",
    text: "What is a part of your story that feels tender to share but important to who you are now? (Reflection #21 for you.)",
  },
  {
    id: "L3-022",
    level: 3,
    type: "question",
    text: "Describe a time you felt deeply unseen or misunderstood in a relationship. (Reflection #22 for you.)",
  },
  {
    id: "L3-023",
    level: 3,
    type: "question",
    text: "What is a fear about intimacy that you rarely say out loud? (Reflection #23 for you.)",
  },
  {
    id: "L3-024",
    level: 3,
    type: "question",
    text: "Share a moment when choosing yourself felt both painful and necessary. (Reflection #24 for you.)",
  },
  {
    id: "L3-025",
    level: 3,
    type: "question",
    text: "How has past hurt shaped the way you protect your heart today? (Reflection #25 for you.)",
  },
  {
    id: "L3-026",
    level: 3,
    type: "question",
    text: "What do you need from someone if you choose to share your hardest memories with them? (Reflection #26 for you.)",
  },
  {
    id: "L3-027",
    level: 3,
    type: "question",
    text: "Describe a time intimacy left you feeling more alone than connected. (Reflection #27 for you.)",
  },
  {
    id: "L3-028",
    level: 3,
    type: "question",
    text: "What is a truth about your desires that you are still learning to accept? (Reflection #28 for you.)",
  },
  {
    id: "L3-029",
    level: 3,
    type: "question",
    text: "When have you felt pressure to be okay when you really were not? (Reflection #29 for you.)",
  },
  {
    id: "L3-030",
    level: 3,
    type: "question",
    text: "What boundary have you held that cost you something, but you would choose again? (Reflection #30 for you.)",
  },
  {
    id: "L3-031",
    level: 3,
    type: "question",
    text: "Share a moment when someone held space for your pain in a way that mattered. (Reflection #31 for you.)",
  },
  {
    id: "L3-032",
    level: 3,
    type: "question",
    text: "How do you carry regret from past relationships, if at all? (Reflection #32 for you.)",
  },
  {
    id: "L3-033",
    level: 3,
    type: "question",
    text: "What is a question about yourself that still feels unanswered? (Reflection #33 for you.)",
  },
  {
    id: "L3-034",
    level: 3,
    type: "question",
    text: "Describe a time you stayed when you knew you needed to leave. (Reflection #34 for you.)",
  },
  {
    id: "L3-035",
    level: 3,
    type: "question",
    text: "How do you know when your body is saying no, even if your mind is confused? (Reflection #35 for you.)",
  },
  {
    id: "L3-036",
    level: 3,
    type: "question",
    text: "What part of your past do you wish could receive more compassion? (Reflection #36 for you.)",
  },
  {
    id: "L3-037",
    level: 3,
    type: "question",
    text: "When have you surprised yourself with your resilience? (Reflection #37 for you.)",
  },
  {
    id: "L3-038",
    level: 3,
    type: "question",
    text: "What is one thing you hope future intimacy will feel like, compared to your past? (Reflection #38 for you.)",
  },
  {
    id: "L3-039",
    level: 3,
    type: "question",
    text: "Describe a moment when you forgave yourself for something difficult. (Reflection #39 for you.)",
  },
  {
    id: "L3-040",
    level: 3,
    type: "question",
    text: "What does true safety in love look like to you, in specific details? (Reflection #40 for you.)",
  },
  {
    id: "L3-041",
    level: 3,
    type: "question",
    text: "What is a part of your story that feels tender to share but important to who you are now? (Reflection #41 for you.)",
  },
  {
    id: "L3-042",
    level: 3,
    type: "question",
    text: "Describe a time you felt deeply unseen or misunderstood in a relationship. (Reflection #42 for you.)",
  },
  {
    id: "L3-043",
    level: 3,
    type: "question",
    text: "What is a fear about intimacy that you rarely say out loud? (Reflection #43 for you.)",
  },
  {
    id: "L3-044",
    level: 3,
    type: "question",
    text: "Share a moment when choosing yourself felt both painful and necessary. (Reflection #44 for you.)",
  },
  {
    id: "L3-045",
    level: 3,
    type: "question",
    text: "How has past hurt shaped the way you protect your heart today? (Reflection #45 for you.)",
  },
  {
    id: "L3-046",
    level: 3,
    type: "question",
    text: "What do you need from someone if you choose to share your hardest memories with them? (Reflection #46 for you.)",
  },
  {
    id: "L3-047",
    level: 3,
    type: "question",
    text: "Describe a time intimacy left you feeling more alone than connected. (Reflection #47 for you.)",
  },
  {
    id: "L3-048",
    level: 3,
    type: "question",
    text: "What is a truth about your desires that you are still learning to accept? (Reflection #48 for you.)",
  },
  {
    id: "L3-049",
    level: 3,
    type: "question",
    text: "When have you felt pressure to be okay when you really were not? (Reflection #49 for you.)",
  },
  {
    id: "L3-050",
    level: 3,
    type: "question",
    text: "What boundary have you held that cost you something, but you would choose again? (Reflection #50 for you.)",
  },
  {
    id: "L3-051",
    level: 3,
    type: "question",
    text: "Share a moment when someone held space for your pain in a way that mattered. (Reflection #51 for you.)",
  },
  {
    id: "L3-052",
    level: 3,
    type: "question",
    text: "How do you carry regret from past relationships, if at all? (Reflection #52 for you.)",
  },
  {
    id: "L3-053",
    level: 3,
    type: "question",
    text: "What is a question about yourself that still feels unanswered? (Reflection #53 for you.)",
  },
  {
    id: "L3-054",
    level: 3,
    type: "question",
    text: "Describe a time you stayed when you knew you needed to leave. (Reflection #54 for you.)",
  },
  {
    id: "L3-055",
    level: 3,
    type: "question",
    text: "How do you know when your body is saying no, even if your mind is confused? (Reflection #55 for you.)",
  },
  {
    id: "L3-056",
    level: 3,
    type: "question",
    text: "What part of your past do you wish could receive more compassion? (Reflection #56 for you.)",
  },
  {
    id: "L3-057",
    level: 3,
    type: "question",
    text: "When have you surprised yourself with your resilience? (Reflection #57 for you.)",
  },
  {
    id: "L3-058",
    level: 3,
    type: "question",
    text: "What is one thing you hope future intimacy will feel like, compared to your past? (Reflection #58 for you.)",
  },
  {
    id: "L3-059",
    level: 3,
    type: "question",
    text: "Describe a moment when you forgave yourself for something difficult. (Reflection #59 for you.)",
  },
  {
    id: "L3-060",
    level: 3,
    type: "question",
    text: "What does true safety in love look like to you, in specific details? (Reflection #60 for you.)",
  },
  {
    id: "L3-061",
    level: 3,
    type: "question",
    text: "What is a part of your story that feels tender to share but important to who you are now? (Reflection #61 for you.)",
  },
  {
    id: "L3-062",
    level: 3,
    type: "question",
    text: "Describe a time you felt deeply unseen or misunderstood in a relationship. (Reflection #62 for you.)",
  },
  {
    id: "L3-063",
    level: 3,
    type: "question",
    text: "What is a fear about intimacy that you rarely say out loud? (Reflection #63 for you.)",
  },
  {
    id: "L3-064",
    level: 3,
    type: "question",
    text: "Share a moment when choosing yourself felt both painful and necessary. (Reflection #64 for you.)",
  },
  {
    id: "L3-065",
    level: 3,
    type: "question",
    text: "How has past hurt shaped the way you protect your heart today? (Reflection #65 for you.)",
  },
  {
    id: "L3-066",
    level: 3,
    type: "question",
    text: "What do you need from someone if you choose to share your hardest memories with them? (Reflection #66 for you.)",
  },
  {
    id: "L3-067",
    level: 3,
    type: "question",
    text: "Describe a time intimacy left you feeling more alone than connected. (Reflection #67 for you.)",
  },
  {
    id: "L3-068",
    level: 3,
    type: "question",
    text: "What is a truth about your desires that you are still learning to accept? (Reflection #68 for you.)",
  },
  {
    id: "L3-069",
    level: 3,
    type: "question",
    text: "When have you felt pressure to be okay when you really were not? (Reflection #69 for you.)",
  },
  {
    id: "L3-070",
    level: 3,
    type: "question",
    text: "What boundary have you held that cost you something, but you would choose again? (Reflection #70 for you.)",
  },
  {
    id: "L3-071",
    level: 3,
    type: "question",
    text: "Share a moment when someone held space for your pain in a way that mattered. (Reflection #71 for you.)",
  },
  {
    id: "L3-072",
    level: 3,
    type: "question",
    text: "How do you carry regret from past relationships, if at all? (Reflection #72 for you.)",
  },
  {
    id: "L3-073",
    level: 3,
    type: "question",
    text: "What is a question about yourself that still feels unanswered? (Reflection #73 for you.)",
  },
  {
    id: "L3-074",
    level: 3,
    type: "question",
    text: "Describe a time you stayed when you knew you needed to leave. (Reflection #74 for you.)",
  },
  {
    id: "L3-075",
    level: 3,
    type: "question",
    text: "How do you know when your body is saying no, even if your mind is confused? (Reflection #75 for you.)",
  },
  {
    id: "L3-076",
    level: 3,
    type: "question",
    text: "What part of your past do you wish could receive more compassion? (Reflection #76 for you.)",
  },
  {
    id: "L3-077",
    level: 3,
    type: "question",
    text: "When have you surprised yourself with your resilience? (Reflection #77 for you.)",
  },
  {
    id: "L3-078",
    level: 3,
    type: "question",
    text: "What is one thing you hope future intimacy will feel like, compared to your past? (Reflection #78 for you.)",
  },
  {
    id: "L3-079",
    level: 3,
    type: "question",
    text: "Describe a moment when you forgave yourself for something difficult. (Reflection #79 for you.)",
  },
  {
    id: "L3-080",
    level: 3,
    type: "question",
    text: "What does true safety in love look like to you, in specific details? (Reflection #80 for you.)",
  },
  {
    id: "L3-081",
    level: 3,
    type: "question",
    text: "What is a part of your story that feels tender to share but important to who you are now? (Reflection #81 for you.)",
  },
  {
    id: "L3-082",
    level: 3,
    type: "question",
    text: "Describe a time you felt deeply unseen or misunderstood in a relationship. (Reflection #82 for you.)",
  },
  {
    id: "L3-083",
    level: 3,
    type: "question",
    text: "What is a fear about intimacy that you rarely say out loud? (Reflection #83 for you.)",
  },
  {
    id: "L3-084",
    level: 3,
    type: "question",
    text: "Share a moment when choosing yourself felt both painful and necessary. (Reflection #84 for you.)",
  },
  {
    id: "L3-085",
    level: 3,
    type: "question",
    text: "How has past hurt shaped the way you protect your heart today? (Reflection #85 for you.)",
  },
  {
    id: "L3-086",
    level: 3,
    type: "question",
    text: "What do you need from someone if you choose to share your hardest memories with them? (Reflection #86 for you.)",
  },
  {
    id: "L3-087",
    level: 3,
    type: "question",
    text: "Describe a time intimacy left you feeling more alone than connected. (Reflection #87 for you.)",
  },
  {
    id: "L3-088",
    level: 3,
    type: "question",
    text: "What is a truth about your desires that you are still learning to accept? (Reflection #88 for you.)",
  },
  {
    id: "L3-089",
    level: 3,
    type: "question",
    text: "When have you felt pressure to be okay when you really were not? (Reflection #89 for you.)",
  },
  {
    id: "L3-090",
    level: 3,
    type: "question",
    text: "What boundary have you held that cost you something, but you would choose again? (Reflection #90 for you.)",
  },
  {
    id: "L3-091",
    level: 3,
    type: "question",
    text: "Share a moment when someone held space for your pain in a way that mattered. (Reflection #91 for you.)",
  },
  {
    id: "L3-092",
    level: 3,
    type: "question",
    text: "How do you carry regret from past relationships, if at all? (Reflection #92 for you.)",
  },
  {
    id: "L3-093",
    level: 3,
    type: "question",
    text: "What is a question about yourself that still feels unanswered? (Reflection #93 for you.)",
  },
  {
    id: "L3-094",
    level: 3,
    type: "question",
    text: "Describe a time you stayed when you knew you needed to leave. (Reflection #94 for you.)",
  },
  {
    id: "L3-095",
    level: 3,
    type: "question",
    text: "How do you know when your body is saying no, even if your mind is confused? (Reflection #95 for you.)",
  },
  {
    id: "L3-096",
    level: 3,
    type: "question",
    text: "What part of your past do you wish could receive more compassion? (Reflection #96 for you.)",
  },
  {
    id: "L3-097",
    level: 3,
    type: "question",
    text: "When have you surprised yourself with your resilience? (Reflection #97 for you.)",
  },
  {
    id: "L3-098",
    level: 3,
    type: "question",
    text: "What is one thing you hope future intimacy will feel like, compared to your past? (Reflection #98 for you.)",
  },
  {
    id: "L3-099",
    level: 3,
    type: "question",
    text: "Describe a moment when you forgave yourself for something difficult. (Reflection #99 for you.)",
  },
  {
    id: "L3-100",
    level: 3,
    type: "question",
    text: "What does true safety in love look like to you, in specific details? (Reflection #100 for you.)",
  },
  {
    id: "W-01",
    level: "wildcard",
    type: "wildcard",
    text: "Swap one answered card with someone of your choice and explain why.",
  },
  {
    id: "W-02",
    level: "wildcard",
    type: "wildcard",
    text: "Reveal a fantasy only in metaphor or symbols. Let others guess the meaning.",
  },
  {
    id: "W-03",
    level: "wildcard",
    type: "wildcard",
    text: "Ask any player a follow-up question from a previous card.",
  },
  {
    id: "W-04",
    level: "wildcard",
    type: "wildcard",
    text: "Act out a brief non-sexual affectionate scene (like a hug or greeting). No words.",
  },
  {
    id: "W-05",
    level: "wildcard",
    type: "wildcard",
    text: "Each player names one boundary they want respected for the next three turns.",
  },
  {
    id: "W-06",
    level: "wildcard",
    type: "wildcard",
    text: "Tell the group one thing about intimacy you never thought you would say out loud.",
  },
  {
    id: "W-07",
    level: "wildcard",
    type: "wildcard",
    text: "Write down a one-line anonymous confession and let someone else read it.",
  },
  {
    id: "W-08",
    level: "wildcard",
    type: "wildcard",
    text: "Check in: each player says whether they want to go lighter, deeper, or pause.",
  },
  {
    id: "W-09",
    level: "wildcard",
    type: "wildcard",
    text: "Invite one player to share a tiny win in their emotional life this week.",
  },
  {
    id: "W-10",
    level: "wildcard",
    type: "wildcard",
    text: "Name one intention you have for how you want to show up in intimacy.",
  },
  {
    id: "GD-01",
    level: "go-deeper",
    type: "go-deeper",
    text: "Share the earliest memory that shaped your idea of closeness or desire. One gentle clarifying question is allowed.",
  },
  {
    id: "GD-02",
    level: "go-deeper",
    type: "go-deeper",
    text: "Describe a moment of tenderness you cherish. Then name one behaviour you\u2019d like more often.",
  },
];

export function allCards(): Card[] {
  return TMT_DECK;
}
